name: Backend Checks

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        env:
          SHA: ${{ github.sha }}
        working-directory: backend
        run: npm install -g eslint prettier

      #   - name: Build
      #     env:
      #       SHA: ${{ github.sha }}
      #     working-directory: backend
      #     run: npm run build --if-present

      - name: Linting
        env:
          SHA: ${{ github.sha }}g
        working-directory: backend
        run: npm run lint

      - name: Format
        env:
          SHA: ${{ github.sha }}
        working-directory: backend
        run: npm run format
        
      - name: Docker Build
        env:
          SHA: ${{ github.sha }}
        working-directory: backend
        run: docker build . -t ci

      - name: Docker Run
        env:
          SHA: ${{ github.sha }}
        working-directory: backend
        run: docker run -p 80:5000 -d ci 

      - name: Unit Tests
        env:
          SHA: ${{ github.sha }}
        working-directory: backend
        run: sleep 5 && npm install -g newman && npm run test
