name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        env:
          SHA: ${{ github.sha }}
        working-directory: app
        run: npm install

      - name: Build
        env:
          SHA: ${{ github.sha }}
        working-directory: app
        run: npm run build --if-present

      - name: Linting
        env:
          SHA: ${{ github.sha }}
        working-directory: app
        run: npm run lint

      - name: Unit Tests
        env:
          SHA: ${{ github.sha }}
        working-directory: app
        run: npm test

      - name: Format
        env:
          SHA: ${{ github.sha }}
        working-directory: app
        run: npm run format
